# Generated by Django 3.0.8 on 2020-07-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_series_seriesvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seriesvideo',
            name='video_url',
            field=models.TextField(),
        ),
    ]
