# Generated by Django 3.0.8 on 2020-07-23 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200723_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='seriesvideo',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Series'),
        ),
        migrations.AlterField(
            model_name='seriesvideo',
            name='video_url',
            field=models.URLField(),
        ),
    ]
