# Generated by Django 3.0.8 on 2020-07-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20200724_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesvideo',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Series'),
        ),
    ]
